services:
  frontend:
    container_name: frontend-service
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - catalog
      - order

  catalog:
    build: ./catalog_service
    ports:
      - "5001:5001"

  order:
    build: ./order_service  
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - CATALOG_REPLICAS=http://catalog1:5003,http://catalog2:5004
      - REPLICA_URLS=http://order2:5005
    networks:
      - bazar-network

  order2:
    build: ./order_service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - CATALOG_REPLICAS=http://catalog1:5003,http://catalog2:5004
      - REPLICA_URLS=http://order1:5002
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge